### ISSUE TITLE
Update strings to be more pythonic - use f-strings

### ISSUE THREAD

**Issue by intendo** [jensengroup/propka#104]
Update all strings to use f-strings rather than using str.format syntax

**Comment by sobolevnrm** [comment]
@speleo3 @orbeckst -- I think one of you suggested this before.  Do you concur?

**Comment by IAlibay** [comment]
Probably worth mentioning this, some very small parts of the codebase now use f-strings as of #85 and #84.

May I suggest taking a strategy where type hinting & f-strings are added progressively as API docs are completed (say for something like #98)?

**Comment by speleo3** [comment]
I like f-strings and certainly use them in new code when possible. But updating existing code with a new pattern is usually low priory for me and it comes with an inherit risk for regressions.

**Comment by intendo** [comment]
Closing issue due to lack of progress and I agree with @speleo3 and @IAlibay that this can be done incrementally over time.
