### ISSUE TITLE
Error: "AttributeError: 'NonCovalentlyCoupledGroups' object has no attribute 'max_intrinsic_pka_diff'"

### ISSUE THREAD

**Issue by ReneHamburger1993** [jensengroup/propka#105]
when running `propka3 -d myfile.pdb` I get this error

OS: RHEL 7.8
propka Version 3.1

Error message:

```
Traceback (most recent call last):
  File "pathtobin/propka3", line 11, in <module>
    load_entry_point('propka', 'console_scripts', 'propka3')()
  File "/propka/run.py", line 33, in main
    my_molecule.calculate_pka()
  File "pathtogitrepo/propka/molecular_container.py", line 87, in calculate_pka
    self.find_non_covalently_coupled_groups()
  File "pathtogitrepo/propka/molecular_container.py", line 68, in find_non_covalently_coupled_groups
    verbose=verbose)
  File "pathtogitrepo/propka/conformation_container.py", line 123, in find_non_covalently_coupled_groups
    NCCG.identify_non_covalently_coupled_groups(self, verbose=verbose)
  File "pathtogitrepo/propka/coupled_groups.py", line 175, in identify_non_covalently_coupled_groups
    info(info_fmt.format(sep=sep, c=self))
AttributeError: 'NonCovalentlyCoupledGroups' object has no attribute 'max_intrinsic_pka_diff'
```

**Comment by ReneHamburger1993** [comment]
the only thing special in my pdb file is that it contains 2 chains that are winded around each other like dna strands.

**Comment by sobolevnrm** [comment]
Would you be willing to share your structure file so we can debug?  You can either post it here (may need to change the file extension to `.txt`) or email it to nathanandrewbaker@gmail.com.  Thank you.

**Comment by ReneHamburger1993** [comment]
Sure I'll send you a mail!

**Comment by sobolevnrm** [comment]
Hello -- 

First, I checked the structure you were using with PDB2PQR:  it has several problems with either formatting or with the structure itself; PDB2PQR reported gaps in the backbone.  I didn't investigate further.  Instead by disabling debumping, I was able to get PDB2PQR to parse the file.

Next, I used the version of PROPKA at the HEAD of the master branch in this repository on the file.  That version of PROPKA also complained about problems with the file but was able to make assignments and calculate pH stability curves.  Please try the latest version of PROPKA from this repo.

Thank you

**Comment by kzinovjev** [comment]
Hello,
I'm having exactly the same problem with a structure that seems totally ok. @sobolevnrm, will email it to you in a second.
Thank you!

**Comment by sobolevnrm** [comment]
> Hello,
> I'm having exactly the same problem with a structure that seems totally ok and using the latest propka. @sobolevnrm, will email it to you in a second.
> Thank you!

Thank you for reporting this.  Have you tried the solution I outlined above?  https://github.com/jensengroup/propka/issues/105#issuecomment-739444561

**Comment by speleo3** [comment]
@sobolevnrm is this issue really fixed? I can still reproduce it with latest `master` and random PDB files (using `-d`).

**Comment by sobolevnrm** [comment]
Thanks for fixing this @speleo3 !
