### ISSUE TITLE
Check the commit I accidentally pushed to master

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#119]
@speleo3 and @orbeckst -- I messed up and pushed https://github.com/jensengroup/propka/commit/d87afb3df55d97080756c3739af1f856d2b5a94d to master. Would you be willing to look over https://github.com/jensengroup/propka/commit/d87afb3df55d97080756c3739af1f856d2b5a94d and comment? I'll address any comments via this (or other new issues).

If I don't receive any comments from you in the next day or so, then I'll release v3.4.0.

**Comment by speleo3** [comment]
Any idea if we can suppress section numbering for the changelog? I really thought for a moment that "5.1.2. Fixes" described the fixes for version 5.1.2.

![screenshot](https://user-images.githubusercontent.com/1239490/102055226-cfa0de00-3dea-11eb-9cb4-3de162f6c0f6.png)

**Comment by sobolevnrm** [comment]
This is difficult to do:  https://github.com/sphinx-doc/sphinx/issues/591

**Comment by speleo3** [comment]
So I guess the only way would be to remove `:numbered:` from [source/index.rst](https://github.com/jensengroup/propka/blob/master/docs/source/index.rst) which removes numbering for all pages.

**Comment by sobolevnrm** [comment]
> So I guess the only way would be to remove `:numbered:` from [source/index.rst](https://github.com/jensengroup/propka/blob/master/docs/source/index.rst) which removes numbering for all pages.

I did that but it didn't remove the numbering in my local version of Sphinx.  Have you tried it; did it work for you?

**Comment by speleo3** [comment]
Yes it works for me. This is what I did after removing `:numbered:`:
```bash
cd docs
rm -rf build
sphinx-build source build
```

**Comment by sobolevnrm** [comment]
> Yes it works for me. This is what I did after removing `:numbered:`:
> 
> ```shell
> cd docs
> rm -rf build
> sphinx-build source build
> ```

OK, I'll give it a try later today.  You could have just posted https://www.youtube.com/watch?v=aCbfMkh940Q :)
