### ISSUE TITLE
propka3.4 predicts pKa of CYS as 99.99 every time. 

### ISSUE THREAD

**Issue by danny305** [jensengroup/propka#122]
I ran propka3.4 on the pdb files 6ij6, 6ilw, and 6ky5 and it consistently predicts the pKa of all CYS residues to be 99.99. I am assuming this is a bug. Its my first time using the software tool.

**Comment by sobolevnrm** [comment]
Do these CYS residues participate in disulfide bridges?

**Comment by danny305** [comment]
Yeah all 4 of them do.

**Comment by sobolevnrm** [comment]
In that case, the 99.99 is the intended behavior.  The code is not able to model coupled redox/titration reactions.  Please let us know if you have any additional questions.  Thanks.
