### ISSUE TITLE
pKa missing for N-ter sidechain

### ISSUE THREAD

**Issue by shaoqx** [jensengroup/propka#137]
I have a HIS on the N-ter and the pKa for the HIS sidechain is missing in the PROPKA3 output. I tested truncate the chain and make a intrachain HIS becomes the N-ter HIS. PROPKA3 give pKa for the former case and not the latter case.

Here are testing pdbs:
[chainA.zip](https://github.com/jensengroup/propka/files/7509374/chainA.zip)

**Comment by sobolevnrm** [comment]
Thank you for filing this bug.  There aren't very many of us monitoring this repository but we will try to address this in due course.

**Comment by sobolevnrm** [comment]
I believe this was fixed in v3.4.0 #259
