### ISSUE TITLE
Handling of metal ions

### ISSUE THREAD

**Issue by guidsari** [jensengroup/propka#142]
Good morning,
I'm trying to use PROPKA3.4 to obtain an estimation of the pKa of an aspartate residue inside a mutant of a small bacterial protein.
My mutant protein includes one Zn2+ ion with a complexed water molecule, not too far from the aspartate.
1) Is it possible for the PROPKA3 software to handle the charged zinc without ignoring it, so that I can estimate the pKa of the water molecule bound to the zinc?
2) In the case this were not possible, can the software handle the Zn2+ charge, since it is relatively close to the aspartate I want to investigate and it could electrostatically influence its dissociation properties?
3) I suppose the software will be able to handle Na+ and Cl- solute ions, am I correct?

Thanks for your kind attention.
Yours sincerely,
Guido Frisari
PhD Student
EPFL - 1015 Lausanne (CH)
SB - ISIC - LCBC (Computational Chemistry and Biochemistry Laboratory - Ursula Roethlisberger's group)
guido.frisari@epfl.ch

**Comment by sobolevnrm** [comment]
I don't think PROPKA is the best choice for this use case.  I'd recommend [MCCE](https://gunnerlab.github.io/Stable-MCCE/) from the Gunner lab instead.

**Comment by sobolevnrm** [comment]
Have you tried this?  What error did you receive?

**Comment by guidsari** [comment]
It complains about histidines which had abnormal protonation states, like in the following case:
Expected 2 interaction atoms for bases, found:
               261- ND1    16-HIS (X) [  34.138   24.262   35.169] N
               265- NE2    16-HIS (X) [  33.107   26.174   34.604] N

Apart from that, it seems to be producing a normal output. Lines are similar to the following ones:

---------  -----   ------   ---------------------    --------------    --------------    --------------
                            DESOLVATION  EFFECTS       SIDECHAIN          BACKBONE        COULOMBIC
 RESIDUE    pKa    BURIED     REGULAR      RE        HYDROGEN BOND     HYDROGEN BOND      INTERACTION
---------  -----   ------   ---------   ---------    --------------    --------------    --------------

ASP  22 X   5.50    91 %    2.17  536   0.00    0    0.00 XXX   0 X   -0.23 ALA  23 X   -0.02 N+    1 X
ASP  22 X                                            0.00 XXX   0 X    0.00 XXX   0 X   -0.17 LYS  28 X
ASP  22 X                                            0.00 XXX   0 X    0.00 XXX   0 X   -0.05 LYS  50 X

ASP  33 X   3.16   100 %    2.86  596   0.45    0   -0.68 LYS  37 X    0.00 XXX   0 X   -0.60 HIS   5 X
ASP  33 X                                            0.00 XXX   0 X    0.00 XXX   0 X   -0.64 HIS  16 X
ASP  33 X                                            0.00 XXX   0 X    0.00 XXX   0 X   -2.03 LYS  37 X
(many other lines)

(another section with pKa and model pKa for each protonable residue)

The output file ends this way:
Free energy of   folding (kcal/mol) as a function of pH (using neutral reference)
  0.00     39.40
  1.00     39.30
  2.00     38.63
  3.00     36.95
  4.00     36.80
  5.00     40.50
  6.00     43.86
  7.00     44.82
  8.00     44.23
  9.00     41.99
 10.00     39.03
 11.00     39.29
 12.00     42.62
 13.00     46.15
 14.00     48.75

The pH of optimum stability is  3.6 for which the free energy is   36.4 kcal/mol at 298K
Could not determine pH values where the free energy is within 80 % of minimum
Could not determine the pH-range where the free energy is negative

Protein charge of folded and unfolded state as a function of pH
    pH  unfolded  folded
  0.00     11.00   10.98
  1.00     10.98   10.81
  2.00     10.83    9.89
  3.00      9.64    8.45
  4.00      5.25    6.69
  5.00      0.48    3.73
  6.00     -1.54   -0.06
  7.00     -3.35   -3.27
  8.00     -4.45   -5.43
  9.00     -5.30   -7.56
 10.00     -7.67   -9.14
 11.00    -12.14  -10.36
 12.00    -13.77  -11.03
 13.00    -13.98  -11.66
 14.00    -14.00  -12.53
The pI is  6.00 (folded) and  5.20 (unfolded)





Now, as you can see, I get a pKa value for ASP33, which is relatively close to a Zn (the aspartate does NOT coordinate the zinc, but it will feel its electromagnetic field; the name of the Zn residue in the PDB is ZN6).
What I don't know is if I can trust the algorithm to work correctly with a Zn2+ ions just a few angstrom far from the aspartate side chain. Moreover, I don't know whether Zn2+ is parametrized in the program.


I can easily neglect Na+ ions because they are far from the protein.
Thank you for your attention.

**Comment by guidsari** [comment]
I forgot to say that the histidines have a weird protonation state because they interact with the Zn2+. I'm using the -k option to keep the original protonation state of each residue. Anyway, I'm not interested in the histidine residues, only in that aspartate.
I would like to know if I can trust the predicted value.

**Comment by sobolevnrm** [comment]
I'm sorry but I don't know how well PROPKA performs with divalent atoms near titratable groups.
