### ISSUE TITLE
 Warning message: Unexpected number (15) of atoms in residue ASN   9 _   in conformation 60A

### ISSUE THREAD

**Issue by mmerlini87** [jensengroup/propka#144]
I'm running some pKa calculations using propKa for a protein and for the same protein in a water environment.
When I use only the protein the code is running fine while in the presence of the water molecules the code is returning the following warning message: 

Unexpected number (15) of atoms in residue ASN   9 _   in conformation 60A

Looking at the code it seems that propKa is reading an inconsistent number of atoms for all the residues.
Could you please explain me what is the reason of this warning?
Could it be that it is due to the fact that the protein is already protonated?

**Comment by sobolevnrm** [comment]
Can you please share the PDB file that is causing the problem?

**Comment by mmerlini87** [comment]
Hi, 

here it is the PDB file causing the warning:

[frame0-WAT.pdf](https://github.com/jensengroup/propka/files/8340855/frame0-WAT.pdf)

**Comment by sobolevnrm** [comment]
@mmerlini87 -- this is not converting to text cleanly.  Could you please post the PDB as a `.txt` or `.zip` file?

**Comment by sobolevnrm** [comment]
I'm going to close this until we get a workable version of the PDB file.
