### ISSUE TITLE
Missing atoms or failed protonation

### ISSUE THREAD

**Issue by rediaz111** [jensengroup/propka#147]
When I try to run `propka 3 filename.pdb -o pH -d`, I receive the following error.

> Missing atoms or failed protonation for TRP 301 A (BBN) -- please check the structure
Group (BBN) for  4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Expected 2 interaction atoms for acids, found:
                 0-  H1   301-TRP (A) [  -0.834   -0.673  -12.919] H
                 0-  H2   301-TRP (A) [  -0.814    0.517  -14.061] H
              4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Expected 2 interaction atoms for bases, found:
                 0-  H1   301-TRP (A) [  -0.834   -0.673  -12.919] H
                 0-  H2   301-TRP (A) [  -0.814    0.517  -14.061] H
              4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Missing atoms or failed protonation for TRP 348 A (BBN) -- please check the structure
Group (BBN) for  5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N
Expected 2 interaction atoms for acids, found:
                 0-  H1   348-TRP (A) [  -3.859   17.366  -29.395] H
                 0-  H2   348-TRP (A) [  -4.843   18.675  -29.203] H
              5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N
Expected 2 interaction atoms for bases, found:
                 0-  H1   348-TRP (A) [  -3.859   17.366  -29.395] H
                 0-  H2   348-TRP (A) [  -4.843   18.675  -29.203] H
              5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N
Missing atoms or failed protonation for TRP 301 A (BBN) -- please check the structure
Group (BBN) for  4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Expected 2 interaction atoms for acids, found:
                 0-  H1   301-TRP (A) [  -0.834   -0.673  -12.919] H
                 0-  H2   301-TRP (A) [  -0.814    0.517  -14.061] H
              4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Expected 2 interaction atoms for bases, found:
                 0-  H1   301-TRP (A) [  -0.834   -0.673  -12.919] H
                 0-  H2   301-TRP (A) [  -0.814    0.517  -14.061] H
              4854-   N   301-TRP (A) [  -1.008    0.307  -13.092] N
Missing atoms or failed protonation for TRP 348 A (BBN) -- please check the structure
Group (BBN) for  5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N
Expected 2 interaction atoms for acids, found:
                 0-  H1   348-TRP (A) [  -3.859   17.366  -29.395] H
                 0-  H2   348-TRP (A) [  -4.843   18.675  -29.203] H
              5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N
Expected 2 interaction atoms for bases, found:
                 0-  H1   348-TRP (A) [  -3.859   17.366  -29.395] H
                 0-  H2   348-TRP (A) [  -4.843   18.675  -29.203] H
              5653-   N   348-TRP (A) [  -4.353   18.104  -29.876] N

I'm not sure how to fix this issue. 
[Apo_refine_50_Up.txt](https://github.com/jensengroup/propka/files/9273896/Apo_refine_50_Up.txt)

**Comment by rediaz111** [comment]
I wanted to follow up on this error that I'm receiving. I don't see anything in the PDB file that points toward what the issue is.

**Comment by trandinhquangloc** [comment]
@rediaz111 
I am getting the same problem with you. No answer -_-
Have you fixed it or know the reasons?

**Comment by sobolevnrm** [comment]
Do either of you have a PDB entry that reproduces the results?  The attachment about looks like a custom PDB file.  

Thanks.

**Comment by rediaz111** [comment]
PDB ID: 8fg5

**Comment by speleo3** [comment]
```sh
propka3 8fg5.pdb -o 7.0 -d
```
Runs without errors or warnings for me, using propka 3.5 or 3.4 (with older versions I get an `AttributeError`).

The attached `Apo_refine_50_Up.txt` has two residues (300 and 347) with Alt code B but no A. If I change those to A, the errors go away.
