### ISSUE TITLE
pKa informed protonation?

### ISSUE THREAD

**Issue by akranc1** [jensengroup/propka#149]
Is there currently any native way in propka to use the calculated pKas to inform the protonation of amino acids in imported pdb files? I essentially need to be able to add all backbone hydrogens, as well as appropriate titratable hydrogens to be added.

**Comment by sobolevnrm** [comment]
You can use [PDB2PQR](http://www.poissonboltzmann.org/) to add hydrogens based on the protonation states assigned by PROPKA.
