### ISSUE TITLE
Please make new release for PyPI

### ISSUE THREAD

**Issue by aszilagyi** [jensengroup/propka#153]
The current release on PyPI has bugs that have since been fixed. E.g. the propka3 command ignores the window and grid settings.

**Comment by sobolevnrm** [comment]
I'll look into this.  At a minimum, I'll need to fix #154 first.

**Comment by sobolevnrm** [comment]
Also #155.

**Comment by sobolevnrm** [comment]
This isn't actually fixed--I still need to submit the PyPI update.

**Comment by sobolevnrm** [comment]
Ta-da!  https://pypi.org/project/propka/3.5.0/

**Comment by aszilagyi** [comment]
Great, thank you!
