### ISSUE TITLE
Pending job start

### ISSUE THREAD

**Issue by axm8099** [jensengroup/propka#162]
I am trying to run PROPKA calculations on a protein using a pdb file upload but the server is stuck on pending job start. It stays loading for hours without getting results. However when I use the pdb file code it runs the results in 33 seconds. The reason why I need to use the file upload is because I need to do manipulation to the enzyme using pymol and export the pdb file from pymol

**Comment by sobolevnrm** [comment]
Can you please provide the URL of the server you used?

**Comment by axm8099** [comment]
Hello Nathan,

I used this link https://server.poissonboltzmann.org/pdb2pqr

Regards,

Alaa Aziz
Teaching Assistant
Department of Chemistry and Biochemistry
University of Texas at Arlington
700 Planetarium Place
Arlington, Texas 76019-0065


From: Nathan Baker ***@***.***>
Date: Saturday, April 15, 2023 at 9:25 PM
To: jensengroup/propka ***@***.***>
Cc: Aziz, Alaa ***@***.***>, Author ***@***.***>
Subject: Re: [jensengroup/propka] Pending job start (Issue #162)

[External]

Can you please provide the URL of the server you used?

**Comment by sobolevnrm** [comment]
This is a [PDB2PQR](https://github.com/Electrostatics/pdb2pqr) issue, not a PROPKA one.  Unfortunately, I cannot transfer this issue between organizations.

However, I was unable to reproduce this issue by downloading and re-uploading the 1FAS PDB entry to the server.  If you continue to have this problem, can you please repost in the [PDB2PQR issues](https://github.com/Electrostatics/pdb2pqr/issues) with more information about how to reproduce the issue?

**Comment by axm8099** [comment]
Hello Nathan,

How do I use the PROPKA server then?
I am trying to have predicted PKa values for my enzyme and some variants. Your help is much appreciated

Regards,

Alaa Aziz
Graduate Teacher Assistant
Department of chemistry and biochemistry
University of Texas at Arlington
700 Planetarium Place
Arlington, Texas 76019-0065

On Apr 16, 2023, at 10:20, Nathan Baker ***@***.***> wrote:

﻿

[External]

Closed #162<https://github.com/jensengroup/propka/issues/162> as completed.

**Comment by sobolevnrm** [comment]
The PDB2PQR server implements PROPKA; you can perform your pKa calculations there.
