### ISSUE TITLE
Calculations take a long time (>1 hour) if there is no chain ID assigned

### ISSUE THREAD

**Issue by matvey83** [jensengroup/propka#19]
Take any PDB file, set chain name to " " for all atoms, and attempt to run it through propka.  Notice that the job takes a long time to run. PPREP-1218

**Comment by speleo3** [comment]
I cannot reproduce this. Setting the chain identifier to " " has no affect on runtime duration in my tests.

**Comment by speleo3** [comment]
Closing this. I found the downstream issue in the Schrodinger script which calls propka. Propka reports empty chain as "_" and the script didn't handle that.
