### ISSUE TITLE
Input file and downloading v3.1

### ISSUE THREAD

**Issue by daviddelima** [jensengroup/propka#191]
Hi, I am currently using propka 3.5, I ran propka3 x.pdb and it only provided the output x.pka. In version 3.1, it shows another output file where we can edit the pka and use it as an input to run the calculation again, how do I do that with v3.5?

Second, how do I install v3.1, is it by this? pip install propka==3.1?

**Comment by daviddelima** [comment]
I was able to install propka3.1 using the command above, my problem is it doesn't respond when I call it using propka or propka3. How do I call it?

**Comment by sobolevnrm** [comment]
`propka3` is the correct way to call the code after installing it with pip:  https://github.com/jensengroup/propka/blob/27e0ad2f8d653404f57c78f1cae2ec32cb5adb68/setup.py#L59

Are you in the same virtual environment as you installed the package?  Is `propka3` in your path?

**Comment by daviddelima** [comment]
Yes and no. I tried troubleshooting it to put it in the path, but every time I install propkav3.1, it doesn't show in the bins.
I also asked you if we can edit the pka input in v3.5, like how it is done in v3.1, as v3.5 doesn't give the other output, only the .pka.

**Comment by daviddelima** [comment]
I get it know, it's not propka3 but propka31!

**Comment by sobolevnrm** [comment]
Great; I'm glad this worked out.  Thank you for the update!
