### ISSUE TITLE
Fix methods to snake case

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#55]
In particular, see

https://github.com/jensengroup/propka-3.1/blob/dde0d67ea5d7b0e8b24a3050ae4d6cbc4ca07972/propka/lib.py#L282

Since the external API is already disrupted, this change shouldn't cause much more trouble.

**Comment by speleo3** [comment]
3 years later: I think we missed the opportunity to break API. Also, to me, snake case vs. camel case has very low priority. I suggest to close this ticket as a "wontfix".
