### ISSUE TITLE
basic documentation

### ISSUE THREAD

**Issue by orbeckst** [jensengroup/propka#69]
At this stage probably the most impactful addition is going to be documentation. Issues #27 and #28 requested the old, defunct tutorials. However, these would be out of date anyway. 

A first milestone would be
- [x] sphinx-based docs
- [ ] hosted on readthedocs or poissonboltzmann.org (the latter can be done with gh-pages and CNAME)
- [x] overview page
- [x] installation (from README)
- [x] quickstart (apply to a PDB, what to look for in the output, key commandline options)
- [x] description of the `propka3` command with its options
- [x] API docs generated from doc strings

If you agree to the general requirements, we can raise individual issues for the parts. Some require more work than others. At this stage, anything is better than nothing, so I would add docs as we go along and perhaps use small tasks here to involve additional contributors.

**Comment by orbeckst** [comment]
@sobolevnrm would you please get https://propka.readthedocs.io/ on ReadTheDocs so that it's clear that you have admin/owner there? I could probably do it but I don't have experience with shifting admin around. 

Once that's there we can just try building docs there. I am starting a sphinx skeleton (PR coming).

**Comment by orbeckst** [comment]
You can see example build at https://becksteinlab.github.io/propka/index.html

**Comment by sobolevnrm** [comment]
I

> @sobolevnrm would you please get https://propka.readthedocs.io/ on ReadTheDocs so that it's clear that you have admin/owner there? I could probably do it but I don't have experience with shifting admin around.
> 
> Once that's there we can just try building docs there. I am starting a sphinx skeleton (PR coming).

Done!  Not much to see at https://propka.readthedocs.io/en/latest/ until @speleo3 approves PR https://github.com/jensengroup/propka/pull/70
