### ISSUE TITLE
problems with predicted pKa of glutamic acid

### ISSUE THREAD

**Issue by Xumin94** [jensengroup/propka#73]
I use different version propka to predict pKa of protein(PDB ID: 1EQC) recently, and find something may be wrong with predicted pKa of glutamic acid(GLU27，GLU51，GLU188 and GLU372), when visualize the structure we don't think these residues should be protonated, but according to the predicted pKa, these residues will be added proton, and I have't find any papers support this. could you give me some advise? or cheak if it is error of the algorithm of propka? 

Thank you!

**Comment by sobolevnrm** [comment]
Hello.  Can you please clarify:  which version of PROPKA did you use?

Thank you

**Comment by Xumin94** [comment]
OK, I have used propka3.0, propka3.1 and propka3.2, and all these generate almost the same result.

**Comment by Xumin94** [comment]
Hello, we may have figure out the reason why PROPKA generate such predicted pKa for these GLU. In 1EQC, these GLU are buried deeply, and maybe the neutral GLU is more reasonable than that with negative charge. If you have other understanding of the question, please share with us.
Thank you so much.

**Comment by sobolevnrm** [comment]
Hi @Xumin94 -- your assessment makes sense to me.  PROPKA penalizes the charging of buried groups due to the low dielectric environment of buried groups.  I'm going to mark this issue as "closed" but please let us know if you have additional questions or concerns.

**Comment by Xumin94** [comment]
Thank you for your detailed answer,
