### ISSUE TITLE
new propka release after 3.2.0

### ISSUE THREAD

**Issue by orbeckst** [jensengroup/propka#86]
With the fixes/re-implementation of StreamIO (#83 , #82) it would be good to have a quick release that downstream projects (such as propkatraj https://github.com/Becksteinlab/propkatraj/issues/20) can build on.

I don't think that propka follows [semantic versioning](https://semver.org/) so @sobolevnrm needs to decide if this should be 3.2.1 or 3.3.0.

**Comment by sobolevnrm** [comment]
We can/should follow semantic versioning.  Did this fix change the API?

**Comment by orbeckst** [comment]
It adds a feature to the 3.2.0 API that is backwards compatible to 3.2.0 – would you agree, @IAlibay @speleo3 ?

As such, semver would prescribe the new version to be 3.3.0.

(Because the difference between 3.1 and 3.2 was massive and certainly not within semantic versioning (which of course made sense in terms of the history of the project), I am just considering 3.2.0 as the baseline for any discussion.)

**Comment by IAlibay** [comment]
> It adds a feature to the 3.2.0 API that is backwards compatible to 3.2.0 – would you agree, @IAlibay @speleo3 ?

Yes, I would agree with that. The `read_molecule_file` function still behaves as expected if used in the way it was being tested in 3.2, and `run.single` was broken in 3.2 for nearly all cases.

**Comment by sobolevnrm** [comment]
> > It adds a feature to the 3.2.0 API that is backwards compatible to 3.2.0 – would you agree, @IAlibay @speleo3 ?
> 
> Yes, I would agree with that. The `read_molecule_file` function still behaves as expected if used in the way it was being tested in 3.2, and `run.single` was broken in 3.2 for nearly all cases.

3.3.0 sounds good to me.  @orbeckst are you willing to update with the new version?  I'll push the new PIP package after.

**Comment by orbeckst** [comment]
The only thing that needs to be done is to tag the master branch with *v3.3.0* (I don’t think that there’s a CHANGELOG or anything else that needs updating). I can do this from GitHub in a moment (typing from a tablet here...)

**Comment by orbeckst** [comment]
There’s 3.3.0 https://github.com/jensengroup/propka/releases/tag/v3.3.0 !

**Comment by sobolevnrm** [comment]
https://pypi.org/project/propka/3.3.0/ Thank you!

**Comment by orbeckst** [comment]
The docs show the release with "3.3.0+0.gcb65c64.dirty" – not entirely sure why. Normally, versioneer+docs works just fine.
