### ISSUE TITLE
Convert parameter files to YAML or JSON?

### ISSUE THREAD

**Issue by sobolevnrm** [jensengroup/propka#94]
@speleo3 and @orbeckst -- what do you think about converting some of the parameter/configuration files to JSON, YAML, or some other human-readable but parseable format?

Thanks,

Nathan

**Comment by speleo3** [comment]
You mean [propka.cfg](https://github.com/jensengroup/propka/blob/master/propka/propka.cfg)? The format looks pretty clean so for me it would not be urgent to change it, but in general it's a good idea to move away from custom parsers. So if someone has the bandwidth to spend time on coming up with a JSON or YAML replacement I wouldn't mind.

**Comment by orbeckst** [comment]
I agree with @speleo3 – good idea, not terribly urgent. 

Are there any parameters that are still hard-coded and not inside files?

**Comment by sobolevnrm** [comment]
I agree.  This isn't a high-priority item; however, we're making some similar changes in PDB2PQR and APBS so I thought I'd see if we could apply them here as well.
