### ISSUE TITLE
KeyError: '1A' with a pdb file

### ISSUE THREAD

**Issue by toontun** [jensengroup/propka#95]
Hello, 

I got a KeyError: '1A' with a specific pdb file (here: [https://ufile.io/udjfm6ez](url)). I don't understand the error. It comes from function "top_up_conformations" of molecular containers... But I don't find any error in my file. 

What's wrong? 

Thanks,
toontun

**Comment by speleo3** [comment]
Change the model number from `0` to `1` on line 3 of your PDB file.
