### ISSUE TITLE
Error: "IndexError: list index out of range" with a specific pdb file

### ISSUE THREAD

**Issue by toontun** [jensengroup/propka#97]
Hello (again), 

I got an error when I try to run propka on this pdb file: https://ufile.io/x7078g3y.

I try on other version of propka and it seems to work.

What's wrong? 

Thank in advance,
Best regards,
toontun

**Comment by sobolevnrm** [comment]
Hello.  I am suspicious of that link.  Can you please attach the file to this issue (may need to add `.txt` to filename per https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

Also, can you please say which version of PROPKA is giving you problems and which one worked in the past?

Thank you

**Comment by toontun** [comment]
Hello, Yes I understand. I attached the file to this issue.

The version which gave me problems is the current version. I cloned this repo and proceeded to a `pip install .` .

After verification , the other version gave me problems too. 

Here the pdb file: 
[antibody1.txt](https://github.com/jensengroup/propka/files/5545245/antibody1.txt)

Thank you

**Comment by sobolevnrm** [comment]
The problem appears to be with 7314-  CG   946-ASN (D) [ 109.540  188.020
98.250] C (ASN 946 on chain D).  Is there anything special about this
residue?

**Comment by toontun** [comment]
No, this residue has nothing particular.

**Comment by speleo3** [comment]
@sobolevnrm I see you self-assigned this, do you already have a solution? Because I think I found the problem (and a solution), the function `BondMaker.put_atom_in_box` doesn't cover all necessary neighbor cells.

**Comment by sobolevnrm** [comment]
> @sobolevnrm I see you self-assigned this, do you already have a solution? Because I think I found the problem (and a solution), the function `BondMaker.put_atom_in_box` doesn't cover all necessary neighbor cells.

I do not have a solution -- thanks for troubleshooting this!

**Comment by toontun** [comment]
Thank you!
